name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: sudo apt install tesseract-ocr & pip install requests pillow pytesseract ddddocr
    - name: Run python script
      run: python demo.py
